version: "3"
services:
  exporter-stue-router:
    image: ghcr.io/tn8or/exporter-tunnel:main
    restart: always
    hostname: exporter-stue-router
    ports:
      - "9101:9100"
    environment:
      HOSTIP: "192.168.50.1"
    volumes:
      - /mnt/storage/sshkey:/app/sshkey:ro
